### ISSUE TITLE
Нюансы

### ISSUE THREAD

**Issue by ZiGNicK** [valevaty98/Insomnia#1]
1) "Все элементы должны быть ярких тонов" - что это значит? Насколько яркие? Разве глаз при чтении не должен отдыхать?
2) "Приложение реализовано на платформе Java; Информация о пользователях и о книгах хранится в базе данных" - почему эти 2 пункта в "Ограничениях"? Больше похоже на способ организации
3) Тяжело читать, слишком часто повторяется "Пользователь" и контент теряется

**Comment by valevaty98** [comment]
1. Спасибо, будет подобрано более корректное описание интерфейса.
2. Это ограничение в использовани технологий.
3. Я не согласен с этим замечанием.

**Comment by valevaty98** [comment]
Исправлено (1 и 2 пункты).
