### ISSUE TITLE
Конструктивное предложение 

### ISSUE THREAD

**Issue by Shvingelskiy** [valevaty98/Insomnia#2]
"Зарегистрированные пользователи - Пользователи, которые вошли в приложение под своим псевдонимом, желающие хранить свои списки книг. Имеют доступ к частичному функционалу"

Укажите пожалуйста, к какому конкретно функционалу будут иметь доступ пользователи.

**Comment by valevaty98** [comment]
Спасибо за змечание. Будут описаны более конкретные возможности зарегестрированных пользователей.

**Comment by valevaty98** [comment]
Исправлено.
